import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:geolocator/geolocator.dart';

class StoreAnalyticsRepository {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Fetches best-selling products.
  /// 
  /// In a production environment, this should query aggregated analytics fields 
  /// (e.g. 'salesCount') generated by a backend. For this MVP, we query active 
  /// products, limit to 20, and sort locally based on existing fields.
  Future<List<Map<String, dynamic>>> getBestSellingProducts({String? category}) async {
    Query<Map<String, dynamic>> query = _firestore
        .collection('store_products')
        .where('status', isEqualTo: 'active');

    if (category != null && category.isNotEmpty && category != 'All') {
      query = query.where('categoryName', isEqualTo: category);
    }
    
    // As a placeholder until order aggregation is built on the backend, we limit the fetch
    // and sort by totalReviews/averageRating to simulate "Best Selling".
    final snapshot = await query.limit(30).get();
    
    var docs = snapshot.docs.map((doc) => {'id': doc.id, ...doc.data()}).toList();
    
    // Attempt to sort by a proxy for sales (like totalReviews if available)
    docs.sort((a, b) {
      final aRating = (a['rating']?['totalReviews'] ?? 0) as int;
      final bRating = (b['rating']?['totalReviews'] ?? 0) as int;
      return bRating.compareTo(aRating);
    });
    
    return docs.take(10).toList();
  }

  /// Fetches top deals based on discount percentages.
  /// 
  /// Queries active products and calculates the discount percentage locally 
  /// to avoid fetching the entire database.
  Future<List<Map<String, dynamic>>> getTopDeals({String? category}) async {
    Query<Map<String, dynamic>> query = _firestore
        .collection('store_products')
        .where('status', isEqualTo: 'active');

    if (category != null && category.isNotEmpty && category != 'All') {
      query = query.where('categoryName', isEqualTo: category);
    }
    
    // Fetch a sample size of active products to calculate discounts.
    // In the future, a 'discountPercentage' field should be maintained by the backend to allow 'orderBy'.
    final snapshot = await query.limit(50).get();
    
    var docs = snapshot.docs.map((doc) => {'id': doc.id, ...doc.data()}).toList();
    
    // Filter to products with an actual discount
    docs = docs.where((data) {
      final price = (data['originalPrice'] ?? data['price'] ?? 0).toDouble();
      final discountPrice = (data['discountPrice'] ?? data['price'] ?? 0).toDouble();
      return price > 0 && discountPrice > 0 && discountPrice < price;
    }).toList();
    
    // Sort by discount percentage descending
    docs.sort((a, b) {
      final aPrice = (a['originalPrice'] ?? a['price'] ?? 0).toDouble();
      final aDiscountPrice = (a['discountPrice'] ?? a['price'] ?? 0).toDouble();
      final aDiscountPct = ((aPrice - aDiscountPrice) / aPrice * 100);
      
      final bPrice = (b['originalPrice'] ?? b['price'] ?? 0).toDouble();
      final bDiscountPrice = (b['discountPrice'] ?? b['price'] ?? 0).toDouble();
      final bDiscountPct = ((bPrice - bDiscountPrice) / bPrice * 100);
      
      return bDiscountPct.compareTo(aDiscountPct);
    });
    
    return docs.take(10).toList();
  }

  /// Fetches today's top picks based on a combined score.
  Future<List<Map<String, dynamic>>> getTopPicks({String? category}) async {
    Query<Map<String, dynamic>> query = _firestore
        .collection('store_products')
        .where('status', isEqualTo: 'active');

    if (category != null && category.isNotEmpty && category != 'All') {
      query = query.where('categoryName', isEqualTo: category);
    }
    
    final snapshot = await query.limit(30).get();
    
    var docs = snapshot.docs.map((doc) => {'id': doc.id, ...doc.data()}).toList();
    
    // Calculate a 'Top Pick' score using simple metrics available.
    docs.sort((a, b) {
      double scoreA = _calculateTopPickScore(a);
      double scoreB = _calculateTopPickScore(b);
      return scoreB.compareTo(scoreA);
    });
    
    return docs.take(10).toList();
  }
  
  double _calculateTopPickScore(Map<String, dynamic> data) {
    // Basic scoring based on ratings and discounts
    final rating = (data['rating']?['average'] ?? 0).toDouble();
    final reviews = (data['rating']?['totalReviews'] ?? 0).toDouble();
    
    final price = (data['originalPrice'] ?? data['price'] ?? 0).toDouble();
    final discountPrice = (data['discountPrice'] ?? data['price'] ?? 0).toDouble();
    final discountPct = price > 0 && discountPrice > 0 && discountPrice < price 
        ? ((price - discountPrice) / price * 100) 
        : 0.0;
        
    // Example: rating is out of 5 (x10 = 50), reviews add some weight, discount adds up to 100 points
    return (rating * 10) + (reviews > 10 ? 10 : reviews) + discountPct;
  }

  /// Fetches nearby products given a user's location.
  Future<List<Map<String, dynamic>>> getNearbyProducts(Position userLocation) async {
    // For a production app, use GeoFlutterFire or a similar geo-hash solution.
    // For this MVP, we query active products and perform a basic distance calculation client-side.
    // Assuming 'store_products' does not have lat/long directly, we might need to fetch the store,
    // or if they do have it, we can filter. Since store_products lacks location data in the model,
    // we fetch active stores, calculate distance, and then fetch products from the top nearby stores.
    
    // 1. Fetch all active stores (limit 50)
    final storeSnapshot = await _firestore.collection('stores')
        .where('status', isEqualTo: 'active')
        .limit(50)
        .get();
        
    List<Map<String, dynamic>> nearbyStoreIds = [];
    
    for (var doc in storeSnapshot.docs) {
      final data = doc.data();
      final address = data['pickupAddress'];
      if (address != null && address['latitude'] != null && address['longitude'] != null) {
        final lat = (address['latitude'] as num).toDouble();
        final lng = (address['longitude'] as num).toDouble();
        
        final distance = Geolocator.distanceBetween(
          userLocation.latitude, userLocation.longitude, 
          lat, lng
        );
        
        // Filter stores within 20km
        if (distance <= 20000) {
          nearbyStoreIds.add({
            'storeId': doc.id,
            'distance': distance
          });
        }
      }
    }
    
    if (nearbyStoreIds.isEmpty) return [];
    
    // Sort stores by distance
    nearbyStoreIds.sort((a, b) => (a['distance'] as double).compareTo(b['distance'] as double));
    
    // Take top 3 closest stores
    final topStoreIds = nearbyStoreIds.take(3).map((e) => e['storeId'] as String).toList();
    
    // 2. Fetch products for those stores
    if (topStoreIds.isEmpty) return [];
    
    final productsSnapshot = await _firestore.collection('store_products')
        .where('status', isEqualTo: 'active')
        .where('storeId', whereIn: topStoreIds)
        .limit(20)
        .get();
        
    return productsSnapshot.docs.map((doc) => {'id': doc.id, ...doc.data()}).toList();
  }
}
